CREATE USER IF NOT EXISTS 'cdc_user'@'%' IDENTIFIED BY 'cdc_pass';

GRANT REPLICATION SLAVE, REPLICATION CLIENT, BINLOG MONITOR ON *.* TO 'cdc_user'@'%';
GRANT SELECT ON `skyhook`.* TO 'cdc_user'@'%';

FLUSH PRIVILEGES;
